### ISSUE TITLE
Issues with Custom model

### ISSUE THREAD

**Issue by ketan-b** [lannguyen0910/food-detection-yolov5#1]
Hi, the repo is great!

The weights associated with this repo are in .pth format, usually the weights are .pt format and the pretrained weights from yolov5 repo are not working here.

Is there a way to convert the .pt weights to .pth and use with your model?

**Comment by kaylode** [comment]
Thank you for your review. And sorry for the late reply.
You are right, it is possible to convert the weights from YoloV5 to match our model's structure, but it will need some modification. You can choose one of these two ways:
1. Use [my template](https://github.com/kaylode/custom-template/tree/detection) to train on your dataset and the weights will fit perfectly in this repo.
2. If you want to convert weights from Yolov5 repo, you have to modify a bit of the source code of that repo, save the model.state_dict() after it is loaded as .pth (or .pt it's not important), you also need to save the class names to the .pth file (because we don't specify them in our code).  Yolov5 authors don't save their model weights by using model.state_dict() (in contrast to ours) but they do in some more complex way; therefore you need to do it manually (we also did this to finetune model :>).
