### ISSUE TITLE
Question about training datasets

### ISSUE THREAD

**Issue by pp1016** [lannguyen0910/food-detection-yolov5#7]
Hi, this is a very impressive work! May I know the public food datasets name that you used for training the model? From the google drive, I only recognize "school lunch", where are the other training data comes from such as old_v1, vn_food? Thanks!

**Comment by lannguyen0910** [comment]
Hi @pp1016, you can refer to my README datasets section [here](https://github.com/lannguyen0910/food-detection-yolov5#-datasets). 
- 3 old versions are from [Open Images V6](https://storage.googleapis.com/openimages/web/index.html). I downloaded all food classes (~80) and 300-400 images per class, splited 80-20. The data is messy (mislabel, wrong bbox) so i recommend you not to use my data, you can download from there and clean the data if you want to use it and to receive good training result.
- You can use [Roboflow](https://app.roboflow.com/) to convert the data to COCO format (because our template support other models besides YOLO so you have to do this step before training). They only allow users to upload 10.000 images (free account) so i splited to 3 versions then converted.

**Comment by lannguyen0910** [comment]
And one thing to remind you, that you can also use the [original YOLOv5 repo](https://github.com/ultralytics/yolov5) to train your food data.  I will update the repo and will not use our own template anymore, we're using old YOLOv5 version to train and it's not good as the latest version.

**Comment by pp1016** [comment]
> And one thing to remind you, that you can also use the [original YOLOv5 repo](https://github.com/ultralytics/yolov5) to train your food data (YOLO format). I will update the repo and will not use our own template anymore, we're using old YOLOv5 version to train and it's not good as the latest version.

Thanks for your reply! I just curious which public food datasets we can use for training the backbone network? I saw your results are pretty good for food region localization! How many datasets are you using? Currently I only use UEC-256 and the results are not good enough... Thanks!

**Comment by lannguyen0910** [comment]
Hi, @pp1016. I used 2 different datasets: Open Images Dataset and VN Food Dataset. I'm currently re-training again with Yolov5 latest version, i think it's gonna be better. I'm planning to use UEC-100 dataset too. May i ask you if you have converted the UEC-256 annotation to YOLO or COCO format? You can make a pull request and i will use it to merge into my dataset. Thank you so much!

**Comment by pp1016** [comment]
> Hi, @pp1016. I used 2 different datasets: Open Images Dataset and VN Food Dataset. I'm currently re-training again with Yolov5 latest version, i think it's gonna be better. I'm planning to use UEC-100 dataset too. May i ask you if you have converted the UEC-256 annotation to YOLO or COCO format? You can make a pull request and i will use it to merge into my dataset. Thank you so much!

Thanks for your reply! Just a suggestion that it would be better if you can put the original dataset link or citation since I am not sure which VF dataset are you using... Another question is that the open image dataset contains not only the food images , therefore if you have an eating scene image containing also some non-food items, so those items will also be detected? I haven't converted it into another format for UEC dataset but just run it using my own code. Thanks for your help!

**Comment by lannguyen0910** [comment]
Hi @pp1016, 
- Like i said in the dataset section, the VN food dataset is our own self-collected dataset, you can refer [README](https://github.com/lannguyen0910/food-detection-yolov5#-datasets). 
- OID has many classes and i only downloaded ~80 food classes from there to train. I didn't use pretrained weights so if you inference a picture contains non-food items, the model won't detect it. Because our main goal is to build a "food detector" to detect accurately as many food as possible, so we are not gonna focus on other things/classes.
- I will update the work with Yolov5 latest version soon, the performance is much much better.
